services:
  data-engineering:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-engineering
    hostname: data-engineering
    ports:
      - "8080:8080"   # Spark Web UI
      - "8088:8088"   # Hadoop ResourceManager UI (optional)
      - "8081:8081"   # Spark Worker UI
      - "9870:9870"   # Hadoop Namenode UI
      - "7077:7077"   # Spark Master
      - "4040:4040"   # Spark App UI
    networks:
      - data-net
    volumes:
      - ./data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: de_project
      MYSQL_USER: de_user
      MYSQL_PASSWORD: de_pass
    ports:
      - "3306:3306"
    networks:
      - data-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  data-net:

volumes:
  mysql-data:
