version: '3'

services:
  spark-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: spark_notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    command: >
      start.sh bash -c "
        jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root & 
        sleep 5 && 
        spark-submit work/job.py && 
        tail -f /dev/null
